name: Deploy static mais Parceiros RJ

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.9.0
          cache: npm
      
      - name: Build
      - run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll
      
      - name: Deploy
      - uses: alimadeoliveiranatalia/mais_parceiros_rj@0.1.0
        with:
          branch: gh-pages
          folder: out